# Generated by Django 4.0.3 on 2022-05-01 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_cablatlong_ip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cabLatLong',
        ),
    ]
